### ISSUE TITLE
Update information for LGI (Lowdham Grange)

### ISSUE THREAD

**Issue by simonnebMOJ** [ministryofjustice/prison-register#216]
Since the 1st of August HMP Lowdham Grange (a Cat B prison with a capacity of just under 1000 adult males) transitioned from being privately operated to being a publicly operated prison.  Background on the reasoning for the transition can be found [here](https://lnks.gd/l/eyJhbGciOiJIUzI1NiJ9.eyJidWxsZXRpbl9saW5rX2lkIjoxMDAsInVyaSI6ImJwMjpjbGljayIsInVybCI6Imh0dHBzOi8vd3d3Lmdvdi51ay9nb3Zlcm5tZW50L25ld3MvaG1wLWxvd2RoYW0tZ3JhbmdlLWNvbnRyYWN0LXRvLXRyYW5zaXRpb24tdG8tcHVibGljLXNlY3Rvci1jb250cm9sIiwiYnVsbGV0aW5faWQiOiIyMDI0MDgwOS45ODgzOTUyMSJ9.mq7YqXpHtibMzv3BIcfG2RHDaFJKU0ljMHNJt1DlO20/s/3118357781/br/247182620719-l).

The information in the prison register needs to be updated. Specifically:

* contracted = false
* operators = PSP

**Comment by ashleygyngell** [comment]
Updated 👍
