### ISSUE TITLE
Update information about Cookham Wood (CKI)

### ISSUE THREAD

**Issue by simonnebMOJ** [ministryofjustice/prison-register#219]
Cookham Wood is now been changed to a male adult prison: https://www.gov.uk/government/news/young-offenders-institution-to-be-repurposed

The information in the register needs to be updated - specifically:

* types
  - code: HMP
  - description: His Majesty’s Prison
* prisonName: Cookham Wood (HMP)

**Comment by ashleygyngell** [comment]
Updated 👍
