### ISSUE TITLE
Fix incorrect postcodes

### ISSUE THREAD

**Issue by simonnebMOJ** [ministryofjustice/prison-register#299]
During some routine work we noticed that some of the postcodes in the prison-register are incorrect. The table below shows the incorrected and corrected postcodes:

| Code | registry prison name   | postcode register | postcode os |
|------|------------------------|-------------------|-------------|
| BWI  | Berwyn (HMP)           | LL13 9QA          | LL13 9QE    |
| CDI  | Chelmsford (HMP & YOI) | CM2 6JT           | CM2 6LQ     |
| FSI  | Featherstone (HMP)     | WV10 7PU          | WV10 7PY    |
| FYI  | Feltham A (HMYOI)      | TW13 4NP          | TW13 4ND    |
| FWI  | Five Wells (HMP)       | NN8 2NG           | NN8 2NX     |
| FEI  | Fosse Way (HMP)        | LE18 4TN          | LE18 4WS    |
| HDI  | Hatfield (HMP & YOI)   | DN7 6FA           | DN7 6EL     |
| WII  | Warren Hill (HMP)      | IP12 3BF          | IP12 3JW    |

**Comment by ashleygyngell** [comment]
@simonnebMOJ Updated apart from Hatfield. It has two addresses?

**Comment by simonnebMOJ** [comment]
Ah yes - Hatfield has two sites - Hatfield Main site and Hatfield Lake site - see [here](https://www.gov.uk/guidance/hatfield-prison). Think we can skip that one. Thanks for sorting - there may be a few more to come.

**Comment by simonnebMOJ** [comment]
Looks like you have put in CM2 6**J**Q for CDI rather than CM2 6**L**Q
